@server=http://localhost:4004
@username1=user1
@password1=user1

@username2=user2
@password2=user2


### Books
# @name Books_GET
GET {{server}}/odata/v4/optimistic-concurrency/Books?$filter=ID eq 7006609
Authorization: Basic  {{username1}}:{{password1}}

### user 1 get Books
GET {{server}}/odata/v4/optimistic-concurrency/getBooks()
Authorization: Basic  {{username1}}:{{password1}}
### Books

GET http://localhost:33831/odata/v4/optimistic-concurrency/Books
Authorization: Basic  {{username2}}:{{password2}}

### Books
# @name Books_POST
POST {{server}}/odata/v4/optimistic-concurrency/Books
Content-Type: application/json
Authorization: Basic {{username2}}:{{password1}}

{
  "ID": 12342,
  "title": "title-8179468",
  "price": 5382513.4,
  "coutry" : "USA",
  "createdAt": "2014-03-05T00:00:00.000Z",
  "createdBy": "createdBy.4vbbg@example.com",
  "modifiedAt": "2017-10-21T00:00:00.000Z",
  "modifiedBy": "modifiedBy.4vbbg@example.net"
}


### Books
# @name Books_PATCH
PATCH http://localhost:41899/odata/v4/optimistic-concurrency/Books/7006609
Authorization: Basic {{username2}}:{{password2}}
Content-Type: application/json
If-Match: W/"2025-12-23T02:35:11.324Z"

{
  "title": "title-sssss"
 
 
}


### Books
# @name Books_DELETE
DELETE {{server}}/odata/v4/optimistic-concurrency/Books/8179468
Content-Type: application/json
Authorization: Basic {{username1}}:{{password1}}
